//changed some solarpanel recipe
ServerEvents.recipes(event => {
    //太阳能板1
    event.shaped(Item.of('solarflux:sp_1',4),[
        'AAA',
        'BCB',
        'BCB',
    ],
    {
        A:'solarflux:mirror',
        B:'minecraft:iron_block',
        C:'enderio:redstone_alloy_ingot',
    })
    event.shaped(Item.of('solarflux:mirror',3),[
        'AAA',
        'BBB',
        'CCC',
    ],{
        A:'minecraft:white_stained_glass_pane',
        B:'minecraft:iron_ingot',
        C:'#minecraft:planks',
    })
   //太阳能板2
   event.shaped(Item.of('solarflux:sp_2',4),[
    'AAA',
    'ABA',
    'AAA',
    ],
    {
    A:'solarflux:sp_1',
    B:'minecraft:piston',
    })
    
    event.shaped(Item.of('solarflux:photovoltaic_cell_1',3),[
        'AAA',
        'BBB',
        'CCC',
    ],{
        A:'minecraft:light_blue_stained_glass_pane',
        B:'minecraft:diamond',
        C:'solarflux:mirror',
    })
    //太阳能板3
    event.shaped(Item.of('solarflux:sp_3',2),[
        'CCC',
        'ABA',
        'ABA',
    ],
    {
        A:'solarflux:sp_2',
        B:'mekanism:elite_control_circuit',
        C:'solarflux:photovoltaic_cell_1',
    })
        
    event.shaped(Item.of('solarflux:photovoltaic_cell_2',3),[
        'AAA',
        'BBB',
        'CCC',
    ],{
        A:'minecraft:blue_stained_glass_pane',
        B:'mekanism:alloy_reinforced',
        C:'solarflux:photovoltaic_cell_1',
    })
    //太阳能板4
    event.shaped(Item.of('solarflux:sp_4',2),[
        'CCC',
        'ABA',
        'ABA',
    ],
    {
        A:'solarflux:sp_3',
        B:'alltheores:enderium_ingot',
        C:'solarflux:photovoltaic_cell_2',
    })
        
    event.shaped(Item.of('solarflux:photovoltaic_cell_3',3),[
        'AAA',
        'BBB',
        'CCC',
    ],{
        A:'minecraft:blue_stained_glass_pane',
        B:'alltheores:enderium_ingot',
        C:'solarflux:photovoltaic_cell_2',
    })
    //太阳能板5
    event.shaped(Item.of('solarflux:sp_5',2),[
        'CCC',
        'ABA',
        'ABA',
    ],
    {
        A:'solarflux:sp_4',
        B:'enderio:end_steel_ingot',
        C:'solarflux:photovoltaic_cell_3',
    })
        
    event.shaped(Item.of('solarflux:photovoltaic_cell_4',3),[
        'AAA',
        'BBB',
        'CCC',
    ],{
        A:'minecraft:blue_stained_glass_pane',
        B:'enderio:end_steel_ingot',
        C:'solarflux:photovoltaic_cell_3',
    })
    //太阳能板6
    event.shaped(Item.of('solarflux:sp_6',2),[
        'CCC',
        'ABA',
        'ABA',
    ],
    {
        A:'solarflux:sp_5',
        B:'create:precision_mechanism',
        C:'solarflux:photovoltaic_cell_4',
    })
        
    event.shaped(Item.of('solarflux:photovoltaic_cell_5',3),[
        'AAA',
        'BBB',
        'CCC',
    ],{
        A:'minecraft:blue_stained_glass_pane',
        B:'create:electron_tube',
        C:'solarflux:photovoltaic_cell_4',
    })
    event.shaped(Item.of('solarflux:photovoltaic_cell_6',3),[
        'AAA',
        'BBB',
        'CCC',
    ],{
        A:'minecraft:blue_stained_glass_pane',
        B:'bigreactors:cyanite_ingot',
        C:'solarflux:photovoltaic_cell_5',
    })
    //太阳能板中子
    event.shaped(Item.of('solarflux:sp_avaritia.neutronium',2),[
        'AAA',
        'CBC',
        'CBC',
    ],{
        A:'draconicevolution:draconium_ingot',
        B:'avaritia:neutron_ingot',
        C:'solarflux:sp_de.chaotic',
    })
    //太阳能板无尽
    event.shaped(Item.of('solarflux:sp_avaritia.infinity',2),[
        'AAA',
        'CBC',
        'CBC',
    ],{
        A:'avaritia:neutron',
        B:'avaritia:infinity_ingot',
        C:'solarflux:sp_avaritia.neutronium',
    })
    //太阳能板7
    event.shaped(Item.of('solarflux:sp_7',2),[
        'CCC',
        'ABA',
        'ABA',
    ],
    {
        A:'solarflux:sp_6',
        B:'draconicevolution:draconium_ingot',
        C:'solarflux:photovoltaic_cell_5',
    })
    //太阳能板7
    event.shaped(Item.of('solarflux:sp_8',2),[
        'CCC',
        'ABA',
        'ABA',
    ],
    {
        A:'solarflux:sp_7',
        B:'draconicevolution:draconium_ingot',
        C:'solarflux:photovoltaic_cell_6',
    })
})